import { Bell, ChevronDown, Command, Database, Menu, Search } from "lucide-react";
import { Logo } from "@/components/brand/Logo";
import type { Dataset, User } from "@/types/insightflow";

interface TopbarProps {
  title: string;
  user: User;
  datasets: Dataset[];
  selectedDatasetId: string;
  onDatasetChange: (id: string) => void;
  onMenu: () => void;
}

export function Topbar({ title, user, datasets, selectedDatasetId, onDatasetChange, onMenu }: TopbarProps) {
  return <header className="sticky top-0 z-20 flex min-h-16 items-center justify-between gap-3 border-b border-white/[.07] bg-[#090d16]/90 px-4 py-2 backdrop-blur-xl sm:px-7" data-testid="app-topbar"><div className="flex min-w-0 items-center gap-3"><button className="rounded-lg p-2 text-slate-400 hover:bg-white/[.05] hover:text-white lg:hidden" onClick={onMenu} data-testid="mobile-menu-button"><Menu className="size-5" /></button><div className="lg:hidden"><Logo compact /></div><div className="hidden items-center gap-2 text-xs text-slate-500 sm:flex"><span>Workspace</span><span className="text-slate-700">/</span><span className="text-slate-200">{title}</span></div><h1 className="truncate font-heading text-sm font-semibold text-slate-100 sm:hidden">{title}</h1></div><div className="flex items-center gap-2 sm:gap-3"><label className="relative hidden items-center lg:flex"><Database className="pointer-events-none absolute left-3 size-3.5 text-blue-400" /><select value={selectedDatasetId} onChange={(event) => onDatasetChange(event.target.value)} className="max-w-[220px] appearance-none truncate rounded-lg border border-white/[.08] bg-white/[.025] py-2 pl-9 pr-8 text-xs text-slate-300 outline-none hover:border-blue-500/30 focus:border-blue-500/50" aria-label="Active dataset" data-testid="topbar-dataset-selector">{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.name.replace(".csv", "")}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2.5 size-3.5 text-slate-600" /></label><button className="hidden items-center gap-2 rounded-lg border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs text-slate-500 transition-colors hover:border-blue-500/30 hover:text-slate-200 md:flex" data-testid="global-search-button"><Search className="size-3.5" />Search<span className="ml-2 flex items-center gap-0.5 rounded border border-white/10 px-1.5 py-0.5 text-[10px] text-slate-600"><Command className="size-2.5" />K</span></button><button className="relative rounded-lg p-2 text-slate-400 transition-colors hover:bg-white/[.05] hover:text-white" data-testid="notifications-button"><Bell className="size-[17px]" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-blue-400" /></button><button className="hidden items-center gap-2 border-l border-white/[.08] pl-3 sm:flex" data-testid="topbar-profile-button"><span className="flex size-8 items-center justify-center rounded-lg bg-blue-500/15 text-[11px] font-bold text-blue-300">{user.initials}</span><ChevronDown className="size-3.5 text-slate-600" /></button></div></header>;
}