import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ShieldAlert } from "lucide-react";
import type { ReactNode } from "react";
import { toast } from "sonner";
import { getAnomalies, resolveAnomaly } from "@/services/anomalyService";
import { AnomalyCard } from "@/components/anomalies/AnomalyCard";
import { SectionHeader } from "@/components/dashboard/SectionHeader";
import { LoadingState } from "@/components/common/LoadingState";
export default function Anomalies() { const client = useQueryClient(); const { data, isLoading, isError } = useQuery({ queryKey: ["anomalies"], queryFn: () => getAnomalies() }); const mutation = useMutation({ mutationFn: resolveAnomaly, onSuccess: () => { void client.invalidateQueries({ queryKey: ["anomalies"] }); toast.success("Anomaly marked as resolved"); } }); const items = data ?? []; return <div className="space-y-7" data-testid="anomalies-page"><SectionHeader eyebrow="Signal monitoring" title="Anomalies" description="A prioritized view of movements outside the expected range, so your team can investigate before they become business problems." action={<div className="flex items-center gap-2 text-xs text-slate-500"><span className="size-2 rounded-full bg-rose-400" />Monitoring live</div>} />{isLoading && <LoadingState rows={4} />}{isError && <div className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-5 text-sm text-rose-200">Anomaly monitoring is temporarily unavailable.</div>}{data && <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Summary icon={<ShieldAlert />} label="Total anomalies" value={items.length} tone="blue" /><Summary icon={<AlertTriangle />} label="High severity" value={items.filter((item) => item.severity === "high").length} tone="rose" /><Summary icon={<AlertTriangle />} label="Medium severity" value={items.filter((item) => item.severity === "medium").length} tone="amber" /><Summary icon={<CheckCircle2 />} label="Resolved" value={items.filter((item) => item.status === "resolved").length} tone="emerald" /></div><div className="space-y-3">{items.map((anomaly) => <AnomalyCard key={anomaly.id} anomaly={anomaly} onResolve={() => mutation.mutate(anomaly.id)} />)}</div></>}</div>; }
function Summary({ icon, label, value, tone }: { icon: ReactNode; label: string; value: number; tone: "blue" | "rose" | "amber" | "emerald" }) { const toneClasses = { blue: "bg-blue-500/10 text-blue-300", rose: "bg-rose-500/10 text-rose-300", amber: "bg-amber-500/10 text-amber-300", emerald: "bg-emerald-500/10 text-emerald-300" }; return <div className="rounded-xl border border-white/[.08] bg-[#101827] p-5"><div className={`flex size-8 items-center justify-center rounded-lg ${toneClasses[tone]}`}>{icon}</div><div className="mt-4 font-mono text-2xl text-white">{value}</div><div className="mt-1 text-xs text-slate-500">{label}</div></div>; }