import { useQuery } from "@tanstack/react-query";
import { Activity, ArrowUpRight, CalendarDays, ChevronDown } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, Pie, PieChart as RechartsPieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getOverviewKPIs } from "@/services/analyticsService";
import { ChartCard } from "@/components/dashboard/ChartCard";
import { KpiCard } from "@/components/dashboard/KpiCard";
import { SectionHeader } from "@/components/dashboard/SectionHeader";
import { InsightCard } from "@/components/insights/InsightCard";
import { LoadingState } from "@/components/common/LoadingState";

const tooltipStyle = { backgroundColor: "#101827", border: "1px solid rgba(255,255,255,.12)", borderRadius: 8, color: "#e2e8f0", fontSize: 11 };

export default function Overview() {
  const { data, isLoading, isError } = useQuery({ queryKey: ["overview"], queryFn: () => getOverviewKPIs(), retry: false });
  return <div className="space-y-7" data-testid="overview-page">
    <SectionHeader eyebrow="January 2025 · Global Ecommerce" title="Good morning, Maya" description="Here’s the latest read on your business performance and the signals worth your attention." action={<button className="flex items-center gap-2 rounded-lg border border-white/[.1] bg-[#101827] px-3.5 py-2.5 text-xs font-medium text-slate-300 hover:border-blue-500/30" data-testid="overview-date-range-button"><CalendarDays className="size-3.5 text-slate-500" />Last 6 months<ChevronDown className="size-3.5 text-slate-600" /></button>} />
    {isLoading && <LoadingState rows={4} />}
    {isError && <div className="rounded-xl border border-rose-500/20 bg-rose-500/5 p-5 text-sm text-rose-200" data-testid="overview-error-state">Your analytics summary couldn’t load. The workspace shell is still available.</div>}
    {data && <>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{data.kpis.map((kpi) => <KpiCard key={kpi.id} kpi={kpi} />)}</div>
      <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]">
        <ChartCard title="Revenue trend" description="Current period vs previous period · ₹ millions" action={<div className="flex items-center gap-3 text-[10px] text-slate-500"><span className="flex items-center gap-1.5"><i className="size-1.5 rounded-full bg-blue-400" />Current</span><span className="flex items-center gap-1.5"><i className="size-1.5 rounded-full bg-slate-600" />Previous</span></div>}>
          <div className="h-[260px]" data-testid="revenue-trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trends} margin={{ top: 8, right: 4, left: -24, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity={.22} /><stop offset="100%" stopColor="#3b82f6" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false} /><XAxis dataKey="month" tick={{ fill: "#64748b", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#64748b", fontSize: 10 }} axisLine={false} tickLine={false} tickFormatter={(value) => `₹${value}M`} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`₹${value}M`, "Revenue"]} /><Area type="monotone" dataKey="current" stroke="#3b82f6" strokeWidth={2.5} fill="url(#revenueFill)" /><Line type="monotone" dataKey="previous" stroke="#475569" strokeWidth={1.5} strokeDasharray="4 4" dot={false} /></AreaChart></ResponsiveContainer></div>
        </ChartCard>
        <ChartCard title="Regional performance" description="Revenue by operating region"><div className="h-[260px]" data-testid="regional-performance-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.regions} layout="vertical" margin={{ top: 0, right: 5, left: 8, bottom: 0 }}><CartesianGrid stroke="rgba(255,255,255,.05)" horizontal={false} /><XAxis type="number" hide /><YAxis type="category" dataKey="region" tick={{ fill: "#94a3b8", fontSize: 11 }} axisLine={false} tickLine={false} width={48} /><Tooltip contentStyle={tooltipStyle} cursor={{ fill: "rgba(255,255,255,.03)" }} formatter={(value) => [`₹${value}M`, "Revenue"]} /><Bar dataKey="revenue" fill="#10b981" radius={[0, 4, 4, 0]} barSize={22} /></BarChart></ResponsiveContainer></div></ChartCard>
      </div>
      <div className="grid gap-4 lg:grid-cols-[1.2fr_1fr_1fr]">
        <ChartCard title="Product performance" description="Top categories by revenue"><div className="h-[250px]" data-testid="product-performance-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.products} layout="vertical" margin={{ top: 0, right: 6, left: 4, bottom: 0 }}><XAxis type="number" hide /><YAxis type="category" dataKey="product" tick={{ fill: "#94a3b8", fontSize: 10 }} axisLine={false} tickLine={false} width={78} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`₹${value}M`, "Revenue"]} /><Bar dataKey="revenue" fill="#8b5cf6" radius={[0, 4, 4, 0]} barSize={18} /></BarChart></ResponsiveContainer></div></ChartCard>
        <ChartCard title="Customer segments" description="Active customer mix"><div className="flex h-[250px] items-center justify-between gap-3"><div className="h-full w-[58%]" data-testid="customer-segments-chart"><ResponsiveContainer width="100%" height="100%"><RechartsPieChart><Pie data={data.segments} dataKey="value" innerRadius="58%" outerRadius="80%" paddingAngle={3} stroke="none">{data.segments.map((segment) => <Cell key={segment.name} fill={segment.color} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`${value}%`, "Customers"]} /></RechartsPieChart></ResponsiveContainer></div><div className="space-y-3">{data.segments.map((segment) => <div key={segment.name} className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full" style={{ backgroundColor: segment.color }} /><span className="text-slate-500">{segment.name}</span><span className="ml-auto font-mono text-slate-200">{segment.value}%</span></div>)}</div></div></ChartCard>
        <ChartCard title="Signal health" description="Data quality and coverage"><div className="flex h-[250px] flex-col justify-center"><div className="flex items-end justify-between"><div><div className="font-mono text-4xl font-semibold text-white">94.8</div><div className="mt-1 text-xs text-slate-500">Signal clarity index</div></div><Activity className="mb-2 size-5 text-emerald-400" /></div><div className="mt-7 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-[94.8%] rounded-full bg-emerald-400" /></div><div className="mt-3 flex justify-between text-[10px] text-slate-600"><span>0 · Noisy</span><span className="text-emerald-400">Excellent</span><span>100</span></div><div className="mt-8 flex items-center gap-2 rounded-lg border border-emerald-500/15 bg-emerald-500/5 p-3 text-xs text-emerald-200"><span className="size-1.5 rounded-full bg-emerald-400" />All systems operational</div></div></ChartCard>
      </div>
      <div><div className="mb-4 flex items-end justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-blue-400">Decision signals</div><h2 className="mt-2 font-heading text-xl font-semibold text-white">Recent insights</h2></div><button className="flex items-center gap-1 text-xs font-semibold text-blue-300 hover:text-blue-200" data-testid="overview-view-insights-button">View all <ArrowUpRight className="size-3.5" /></button></div><div className="grid gap-4 lg:grid-cols-3">{data.insights.map((insight) => <InsightCard key={insight.id} insight={insight} compact />)}</div></div>
    </>}
  </div>;
}